apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: omicron-ingress-log
  annotations:
    kubernetes.io/ingress.class: nginx-log
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: seqlog-svc
          servicePort: 81
        path: /