apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: omicron-ingress-log
  annotations:
    kubernetes.io/ingress.class: nginx-log
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - omicronlabloguat.eastus2.cloudapp.azure.com
    secretName: tls-secret-log
  rules:
  - host: omicronlabloguat.eastus2.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: seqlog-svc
          servicePort: 81
        path: /