apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: omicron-ingress-log
  annotations:
    kubernetes.io/ingress.class: nginx-log    
    cert-manager.io/issuer: selfsigned-issuer
spec:
  tls:
  - secretName: selfsigned-cert-tls
    hosts:
    - omicron-log.eastus2.cloudapp.azure.com
  rules:
  - host: omicron-log.eastus2.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: seqlog-svc
          servicePort: 81
        path: /
