apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-oauthserver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: oauthserver-svc
                port:
                  number: 80
            path: /api/oauth(/|$)(.*)
            pathType: Prefix
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://oauthserver-svc.default.svc.cluster.local/oauthrs/validate"
    nginx.ingress.kubernetes.io/auth-method: "GET"
    #If you need services redirect to login on fail, uncomment this line
    #nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/auth-snippet: |
      set $auth_header $http_authorization;
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: catalogos-svc
                port:
                  number: 80
            path: /api/catalogos(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: usuarios-svc
                port:
                  number: 80
            path: /api/usuarios(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: sapadapter-svc
                port:
                  number: 80
            path: /api/sapadapter(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: pedidos-svc
                port:
                  number: 80
            path: /api/pedidos(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: warehouses-svc
                port:
                  number: 80
            path: /api/warehouses(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: reporting-svc
                port:
                  number: 80
            path: /api/reporting(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: reporting-svc
                port:
                  number: 80
            path: /api/reporting(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: almacen-svc
                port:
                  number: 80
            path: /api/almacen(/|$)(.*)
            pathType: Prefix
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dxp-services
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy-svc.default.svc.cluster.local/oauth2/auth"
    #If you need services redirect to login on fail, uncomment this line
    #nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: catalogsdxp-svc
                port:
                  number: 80
            path: /api/dxp/catalog(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: favorites-svc
                port:
                  number: 80
            path: /api/dxp/favorites(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: sapordersadapter-svc
                port:
                  number: 80
            path: /api/dxp/sapordersadapter(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: shoppingcart-svc
                port:
                  number: 80
            path: /api/dxp/shoppingcart(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: advisor-svc
                port:
                  number: 80
            path: /api/dxp/advisor(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: notifications-svc
                port:
                  number: 80
            path: /api/dxp/notifications(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: doctor-svc
                port:
                  number: 80
            path: /api/dxp/doctors(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: files-svc
                port:
                  number: 80
            path: /api/dxp/files(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: processpayment-svc
                port:
                  number: 80
            path: /api/dxp/processpayments(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: payments-svc
                port:
                  number: 80
            path: /api/dxp/payments(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: pedidosdxp-svc
                port:
                  number: 80
            path: /api/dxp/pedidosdxp(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: discounts-svc
                port:
                  number: 80
            path: /api/dxp/discounts(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: incidence-svc
                port:
                  number: 80
            path: /api/dxp/incidencia(/|$)(.*)
          - backend:
              service:
                name: reportdxp-svc
                port:
                  number: 80
            path: /api/dxp/report(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: credit-svc
                port:
                  number: 80
            path: /api/dxp/credit(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: dhladapter-svc
                port:
                  number: 80
            path: /api/dxp/dhladapter(/|$)(.*)
            pathType: Prefix
  ingressClassName: nginx
