apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: omicron-ingress-api
  annotations:
    kubernetes.io/ingress.class: nginx-api
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - secretName: secure-tls
    hosts:
    - magistralesprod.omicronlab.com.mx
  rules:
  - host: magistralesprod.omicronlab.com.mx
    http:
      paths:
      - backend:
          serviceName: apimanager-svc
          servicePort: 8000
        path: /