apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omicroningress-api
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx-api
  tls:
    - secretName: tls-secret
      hosts:
        - omicron-api.eastus2.cloudapp.azure.com
  rules:
    - host: omicron-api.eastus2.cloudapp.azure.com
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: apimanager-svc
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  name: omicroningress-log
spec:
  ingressClassName: nginx-log
  tls:
    - secretName: tls-secret
      hosts:
        - omicron-log.eastus2.cloudapp.azure.com
  rules:
    - host: omicron-log.eastus2.cloudapp.azure.com
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: seqlog-svc
                port:
                  number: 81
          # - pathType: Prefix
          #   path: /
          #   backend:
          #     service:
          #       name: seqlog-svc
          #       port:
          #         number: 5341
