apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: omicron-ingress-api
  annotations:
    kubernetes.io/ingress.class: nginx-api
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - omicronlabapiuat.eastus2.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: omicronlabapiuat.eastus2.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: apimanager-svc
          servicePort: 8000
        path: /
