apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: omicron-ingress-log
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx-log
  tls:
    - secretName: secure-tls-prod
      hosts:
        - magistralesdashboard.omicronlab.com.mx
  rules:
    - host: magistralesdashboard.omicronlab.com.mx
      http:
        paths:
          - backend:
              service:
                name: seqlog-svc
                port:
                  number: 81
            path: /
            pathType: ImplementationSpecific
