apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: omicron-ingress-api
  annotations:
    kubernetes.io/ingress.class: nginx-api    
    cert-manager.io/issuer: selfsigned-issuer
spec:
  tls:
  - secretName: selfsigned-cert-tls
    hosts:
    - omicron-api.eastus2.cloudapp.azure.com
  rules:
  - host: omicron-api.eastus2.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: apimanager-svc
          servicePort: 8000
        path: /