apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: omicron-ingress-log
  annotations:
    kubernetes.io/ingress.class: nginx-log    
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - host: omicronloguat.eastus2.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: seqlog-svc
          servicePort: 81
        path: /