apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver-deployment
  labels:
    app: oauthserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthserver
  template:
    metadata:
      labels:
        app: oauthserver
    spec:
      containers:
        - name: oauthserver
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/oauthservermagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: SPRING_PROFILES_ACTIVE
              value: qa
            - name: POSTGRESS_JDBC_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: omicron_jdbc_postgress_db
          ports:
            - containerPort: 8090
          resources:
            limits:
              cpu: 244m
              memory: 853Mi
            requests:
              cpu: 3m
              memory: 432Mi
---
apiVersion: v1
kind: Service
metadata:
  name: oauthserver-svc
  labels:
    app: oauthserver
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8090
  selector:
    app: oauthserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogos-deployment
  labels:
    app: catalogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogos
  template:
    metadata:
      labels:
        app: catalogos
    spec:
      containers:
        - name: catalogos
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/catalogosmagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: omicron_net_postgress_db
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: redis_connection_string
            - name: SEQLOG_SVC_SERVICE_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: seqlog_svc_service_host_name
          ports:
            - containerPort: 9010
          resources:
            limits:
              cpu: 36m
              memory: 217Mi
            requests:
              cpu: 3m
              memory: 152Mi
---
apiVersion: v1
kind: Service
metadata:
  name: catalogos-svc
  labels:
    app: catalogos
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: catalogos
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
  labels:
    app: usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/usuariosmagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: omicron_net_postgress_db
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: redis_connection_string
            - name: SEQLOG_SVC_SERVICE_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: seqlog_svc_service_host_name
          ports:
            - containerPort: 5101
          resources:
            limits:
              cpu: 279m
              memory: 550Mi
            requests:
              cpu: 4m
              memory: 232Mi
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-svc
  labels:
    app: usuarios
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: usuarios
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapadapter-deployment
  labels:
    app: sapadapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapadapter
  template:
    metadata:
      labels:
        app: sapadapter
    spec:
      containers:
        - name: sapadapter
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/sapadaptermagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: SAP_CONNECTION_STRING_SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: sap_connection_string_sql_server
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: redis_connection_string
            - name: SEQLOG_SVC_SERVICE_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: seqlog_svc_service_host_name
          ports:
            - containerPort: 5102
          resources:
            limits:
              cpu: 623m
              memory: 989Mi
            requests:
              cpu: 9m
              memory: 371Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sapadapter-svc
  labels:
    app: sapadapter
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: sapadapter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
  labels:
    app: pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
        - name: pedidos
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/pedidosmagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: omicron_net_postgress_db
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: redis_connection_string
            - name: KAFKA_EH_FQDN
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_eh_fqdn
            - name: KAFKA_INSERTLOGS_EH_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_insertlogs_eh_name
            - name: SEQLOG_SVC_SERVICE_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: seqlog_svc_service_host_name
            - name: KAFKA_FINALIZEPRODUCTIONORDERSAP_EH_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_finalizeproductionordersap_eh_name
            - name: KAFKA_FINALIZEPRODUCTIONORDERSAP_CONSUMER_GROUP
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_finalizeproductionordersap_consumer_group
            - name: KAFKA_FINALIZEPRODUCTIONORDERPOSTGRESQL_EH_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_finalizeproductionorderpostgresql_eh_name
            - name: KAFKA_FINALIZEPRODUCTIONORDERPOSTGRESQL_CONSUMER_GROUP
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_finalizeproductionorderpostgresql_consumer_group
            - name: KAFKA_PRODUCTIONORDERPDFGENERATION_EH_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_productionorderpdfgeneration_eh_name
            - name: KAFKA_PRODUCTIONORDERPDFGENERATION_CONSUMER_GROUP
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_productionorderpdfgeneration_consumer_group
            - name: KAFKA_EH_FQDN_2
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_eh_fqdn
            - name: KAFKA_RETRYFINALIZEORDER_EH_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_retryfinalizeorder_eh_name                    
            - name: KAFKA_RETRYFINALIZEORDER_EH_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_retryfinalizeorder_eh_connection
            - name: KAFKA_RETRYFINALIZEORDER_CONSUMER_GROUP
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: kafka_retryfinalizeorder_consumer_group                  
          ports:
            - containerPort: 5103
          resources:
            limits:
              cpu: 519m
              memory: 1106Mi
            requests:
              cpu: 87m
              memory: 460Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-svc
  labels:
    app: pedidos
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: pedidos
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouses-deployment
  labels:
    app: warehouses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouses
  template:
    metadata:
      labels:
        app: warehouses
    spec:
      containers:
        - name: warehouses
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/warehousesmagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: omicron_net_postgress_db
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: redis_connection_string
            - name: SEQLOG_SVC_SERVICE_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: seqlog_svc_service_host_name
          ports:
            - containerPort: 5104
          resources:
            limits:
              cpu: 88m
              memory: 223Mi
            requests:
              cpu: 2m
              memory: 172Mi
---
apiVersion: v1
kind: Service
metadata:
  name: warehouses-svc
  labels:
    app: warehouses
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: warehouses
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-deployment
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/reportingmagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: redis_connection_string
            - name: SEQLOG_SVC_SERVICE_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: seqlog_svc_service_host_name
          ports:
            - containerPort: 5105
          resources:
            limits:
              cpu: 58m
              memory: 215Mi
            requests:
              cpu: 4m
              memory: 117Mi
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-svc
  labels:
    app: reporting
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: reporting
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapservicelayeradapter-deployment
  labels:
    app: sapservicelayeradapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapservicelayeradapter
  template:
    metadata:
      labels:
        app: sapservicelayeradapter
    spec:
      containers:
        - name: sapservicelayeradapter
          image: 891376991292.dkr.ecr.us-east-2.amazonaws.com/sapservicelayeradaptermagistrales:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: SAP_SERVICE_LAYER_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: sap_service_layer_url
            - name: SAP_SERVICE_LAYER_USER
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: sap_service_layer_user
            - name: SAP_SERVICE_LAYER_PWD
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: sap_service_layer_pwd
            - name: SAP_SERVICE_LAYER_DB
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: sap_service_layer_db
            - name: SAP_FILE_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: sap_file_url
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: redis_connection_string
            - name: SEQLOG_SVC_SERVICE_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: omicron-qa
                  key: seqlog_svc_service_host_name
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 1m
              memory: 40Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sapservicelayeradapter-svc
  labels:
    app: sapservicelayeradapter
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: sapservicelayeradapter
  type: ClusterIP
