apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-oauthserver
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx-omicron
  tls:
    - hosts:
        - omicronqa.axity.com
      secretName: secure-tls-2024
  rules:
    - host: omicronqa.axity.com
      http:
        paths:
          - backend:
              service:
                name: oauthserver-svc
                port:
                  number: 80
            path: /api/oauth(/|$)(.*)
            pathType: Prefix
