apiVersion: v1
kind: Secret
metadata:
  name: omicron-qa
data:
  omicron_net_postgress_db: U2VydmVyPWRiLWNsdXN0ZXItb21pY3Jvbi5jbHVzdGVyLWNyMml3dWMyNGw2ZS51cy1lYXN0LTIucmRzLmFtYXpvbmF3cy5jb207UG9ydD01NDMyO1VpZD1vbWljcm9uYXBwO1B3ZD01YTY3N0d5a24tVHg7RGF0YWJhc2U9b21pY3Jvbg==
  omicron_net_postgress_db_dxp: U2VydmVyPWRiLWNsdXN0ZXItb21pY3Jvbi5jbHVzdGVyLWNyMml3dWMyNGw2ZS51cy1lYXN0LTIucmRzLmFtYXpvbmF3cy5jb207UG9ydD01NDMyO1VpZD1vbWljcm9uYXBwO1B3ZD01YTY3N0d5a24tVHg7RGF0YWJhc2U9b21pY3Jvbl9keHA=
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1CQ1BfT21pY3JvbmxhYl8xOTA0MjAyMjt1c2VyIGlkPUF4aXR5VXNlclByb2Q7cGFzc3dvcmQ9QXh5MjAxM1I7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7Q29ubmVjdGlvbiBUaW1lb3V0PTU7
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: QkNQX09taWNyb25sYWJfMTkwNDIwMjI=
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTAzL1NhcEZpbGUv