apiVersion: v1
kind: Secret
metadata:
  name: omicron-qa
data:
  keycloak_jdbc: amRiYzpwb3N0Z3Jlc3FsOi8vZGItY2x1c3Rlci1vbWljcm9uLWluc3RhbmNlLTEuY3IyaXd1YzI0bDZlLnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2tleWNsb2Fr
  keycloak_jdbc_user: b21pY3JvbmFwcA==
  keycloak_jdbc_psw: NWE2NzdHeWtuLVR4
  omicron_net_postgress_db: U2VydmVyPWRiLWNsdXN0ZXItb21pY3Jvbi5jbHVzdGVyLWNyMml3dWMyNGw2ZS51cy1lYXN0LTIucmRzLmFtYXpvbmF3cy5jb207UG9ydD01NDMyO1VpZD1vbWljcm9uYXBwO1B3ZD01YTY3N0d5a24tVHg7RGF0YWJhc2U9b21pY3Jvbg==
  omicron_net_postgress_db_dxp: U2VydmVyPWRiLWNsdXN0ZXItb21pY3Jvbi5jbHVzdGVyLWNyMml3dWMyNGw2ZS51cy1lYXN0LTIucmRzLmFtYXpvbmF3cy5jb207UG9ydD01NDMyO1VpZD1vbWljcm9uYXBwO1B3ZD01YTY3N0d5a24tVHg7RGF0YWJhc2U9b21pY3Jvbl9keHA=
  omicron_jdbc_postgress_db: amRiYzpwb3N0Z3Jlc3FsOi8vZGItY2x1c3Rlci1vbWljcm9uLWluc3RhbmNlLTEuY3IyaXd1YzI0bDZlLnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL29taWNyb24/dXNlcj1vbWljcm9uYXBwJnBhc3N3b3JkPTVhNjc3R3lrbi1UeA==
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1CQ1BfT21pY3JvbmxhYl8xOTA0MjAyMjt1c2VyIGlkPUF4aXR5VXNlclByb2Q7cGFzc3dvcmQ9QXh5MjAxM1I7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7Q29ubmVjdGlvbiBUaW1lb3V0PTU7
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: QkNQX09taWNyb25sYWJfMTkwNDIwMjI=
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTAzL1NhcEZpbGUv
  redis_connection_string: cmVkaXMtc3ZjLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OSxwYXNzd29yZD1pa0s2NjhYLjY6a1YsYWJvcnRDb25uZWN0PUZhbHNl
  elastic_url: aHR0cDovL2VsYXN0aWM6WENkOGQyODhGU1ExMzQwWTU0eVhzekpvQGVsYXN0aWNzZWFyY2gtZXMtaHR0cDo5MjAw
  kafka_eh_fqdn: a2Fma2E6OTA5Mg==
  kafka_report_eh_name: cmVwb3J0cWE=
  kafka_report_consumer_group: cmVwb3J0cWE=
  kafka_report_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1yZXBvcnRwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PUF1dnNEc0JuVWNZZE1pd1JSU3prS2sxVFhFK3RQMFVVc2xQYm44OTNMY3M9O0VudGl0eVBhdGg9cmVwb3J0cWE=
  kafka_creditpayment_eh_name: Y3JlZGl0cGF5bWVudHFh
  kafka_creditpayment_consumer_group: Y3JlZGl0cGF5bWVudHFh
  kafka_creditpayment_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1jcmVkaXRwYXltZW50cWFwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PTh1UU85MHBQdVR0TG4vMXhKUEp3aWFTOUtFbkhCaWsrYU5JdmdUSlgvdFU9O0VudGl0eVBhdGg9Y3JlZGl0cGF5bWVudHFhMXhKUEp3aWFTOUtFbkhCaWsrYU5JdmdUSlgvdFU9O0VudGl0eVBhdGg9Y3JlZGl0cGF5bWVudHFh
  kafka_paypalpayment_eh_name: cGF5cGFscGF5bWVudHFh
  kafka_paypalpayment_consumer_group: cGF5cGFscGF5bWVudHFh
  kafka_paypalpayment_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1wYXlwYWxwYXltZW50cG9saWN5O1NoYXJlZEFjY2Vzc0tleT1xVThrcWRyY1UrMTZ1N3JNUERRQkphdGE1cFJoSjgxc2ZnRTB1RmJIcUZnPTtFbnRpdHlQYXRoPXBheXBhbHBheW1lbnRxYQ==
  kafka_bbvapayment_eh_name: YmJ2YXBheW1lbnRxYQ==
  kafka_bbvapayment_consumer_group: YmJ2YXBheW1lbnRxYQ==
  kafka_bbvapayment_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1iYnZhcGF5bWVudHBvbGljeTtTaGFyZWRBY2Nlc3NLZXk9d0Q0OWFDeWtqdTlIbjJBV1pPRDlHa2N6cGI5Uy8xZ2dqdU1zcmtkYzhxUT07RW50aXR5UGF0aD1iYnZhcGF5bWVudHFh
  kafka_validationorder_eh_name: dmFsaWRhdGlvbm9yZGVycWE=
  kafka_validationorder_consumer_group: dmFsaWRhdGlvbm9yZGVycWE=
  kafka_validationorder_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT12YWxpZGF0aW9ub3JkZXJwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PW90cG1UUStmU2dndnhSVXZ0YUJVRTE3bThNS2xKTjlnTStBRWhPaUcxT2c9O0VudGl0eVBhdGg9dmFsaWRhdGlvbm9yZGVycWE=
  kafka_promotionalemails_eh_name: cHJvbW90aW9uYWxlbWFpbHNxYQ==
  kafka_promotionalemails_consumer_group: cHJvbW90aW9uYWxlbWFpbHNxYQ==
  kafka_promotionalemails_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1wcm9tb3Rpb25hbGVtYWlsc3FhcG9saWN5O1NoYXJlZEFjY2Vzc0tleT1vcldheXhlYk9LbUZqbTNwWERXMEtlTzhDOVEwYndHVlhFL2NRSUpBNUdNPTtFbnRpdHlQYXRoPXByb21vdGlvbmFsZW1haWxzcWE=
  kafka_promotionalemailsresend_eh_name: cHJvbW90aW9uYWxlbWFpbHNyZXNlbmRxYQ==
  kafka_promotionalemailsresend_consumer_group: cHJvbW90aW9uYWxlbWFpbHNyZXNlbmRxYQ==
  kafka_promotionalemailsresend_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1wcm9tb3Rpb25hbGVtYWlsc3Jlc2VuZHFhcG9saWN5O1NoYXJlZEFjY2Vzc0tleT1MSFV1Vk5VRlZjVmFEMjFjeHdGQzU5Z3FmVUMxMTFMd0I2T1gvbVNEZW13PTtFbnRpdHlQYXRoPXByb21vdGlvbmFsZW1haWxzcmVzZW5kcWE=
  kafka_insertlogs_eh_name: aW5zZXJ0bG9ncw==
  keycloak_api_pwd: QHhpdHkuMjAyMQ==
  keycloak_api_url: aHR0cHM6Ly9vbWljcm9ucWEuYXhpdHkuY29tL2F1dGgv
  dxp_front_url: aHR0cHM6Ly9kMTMzYTF4ZGhucDhvMi5jbG91ZGZyb250Lm5ldC9ob21l
  seqlog_svc_service_host_name: c2VxbG9nLXN2Yy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs