apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver-deployment
  labels:
    app: oauthserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthserver
  template:
    metadata:
      labels:
        app: oauthserver
    spec:
      containers:
        - name: oauthserver
          image: omicron_omicron.azurecr.io/omicronuat/omicron-appiosformulas-oauthserver-repository-uat:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: SPRING_PROFILES_ACTIVE
              value: uat
            - name: POSTGRESS_JDBC_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: omicron_jdbc_postgress_db
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1413m
              memory: 403Mi
            requests:
              cpu: 354m
              memory: 101Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: oauthserver-svc
  labels:
    app: oauthserver
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: oauthserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogos-deployment
  labels:
    app: catalogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogos
  template:
    metadata:
      labels:
        app: catalogos
    spec:
      containers:
        - name: catalogos
          image: omicron_omicron.azurecr.io/omicronuat/omicron-appiosformulas-catalogos-repository-uat:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Uat
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: omicron_net_postgress_db
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 99m
              memory: 218Mi
            requests:
              cpu: 23m
              memory: 55Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: catalogos-svc
  labels:
    app: catalogos
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: catalogos
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
  labels:
    app: usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: omicron_omicron.azurecr.io/omicronuat/omicron-appiosformulas-usuarios-repository-uat:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Uat
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: omicron_net_postgress_db
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 168m
              memory: 330Mi
            requests:
              cpu: 42m
              memory: 83Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-svc
  labels:
    app: usuarios
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: usuarios
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapadapter-deployment
  labels:
    app: sapadapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapadapter
  template:
    metadata:
      labels:
        app: sapadapter
    spec:
      containers:
        - name: sapadapter
          image: omicron_omicron.azurecr.io/omicronuat/omicron-appiosformulas-sapadapter-repository-uat:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Uat
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: redis
            - name: SAP_CONNECTION_STRING_SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: sap_connection_string_sql_server
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 308m
              memory: 1145Mi
            requests:
              cpu: 77m
              memory: 287Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: sapadapter-svc
  labels:
    app: sapadapter
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: sapadapter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
  labels:
    app: pedidos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
        - name: pedidos
          image: omicron_omicron.azurecr.io/omicronuat/omicron-appiosformulas-pedidos-repository-uat:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Uat
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: redis
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: omicron_net_postgress_db
            - name: EVENHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: eventhub_net_connection
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 183m
              memory: 2675Mi
            requests:
              cpu: 46m
              memory: 669Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-svc
  labels:
    app: pedidos
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: pedidos
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouses-deployment
  labels:
    app: warehouses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouses
  template:
    metadata:
      labels:
        app: warehouses
    spec:
      containers:
        - name: warehouses
          image: omicron_omicron.azurecr.io/omicronuat/omicron-appiosformulas-warehouses-repository-uat:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Uat
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-uat
                  key: omicron_net_postgress_db
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 124m
              memory: 97Mi
            requests:
              cpu: 31m
              memory: 25Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: warehouses-svc
  labels:
    app: warehouses
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: warehouses
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-deployment
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: omicron_omicron.azurecr.io/omicronuat/omicron-appiosformulas-reporting-repository-uat:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Uat
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 45m
              memory: 178Mi
            requests:
              cpu: 12m
              memory: 45Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-svc
  labels:
    app: reporting
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: reporting
  type: ClusterIP
---
