apiVersion: v1
kind: Secret
metadata:
  name: omicron-uat
data:
  omicron_net_postgress_db: U2VydmVyPW9taWNyb251YXQucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tO0RhdGFiYXNlPW9taWNyb25fdWF0O1BvcnQ9NTQzMjtVc2VyIElkPW9taWNyb25hZG1pbjtQYXNzd29yZD1IQFNoMUNvUjMhO1NzbCBNb2RlPVJlcXVpcmU7VHJ1c3QgU2VydmVyIENlcnRpZmljYXRlPXRydWU7VGltZVpvbmU9QW1lcmljYS9NZXhpY29fQ2l0eTs=
  omicron_jdbc_postgress_db: amRiYzpwb3N0Z3Jlc3FsOi8vb21pY3JvbnVhdC5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9vbWljcm9uX3VhdD91c2VyPW9taWNyb25hZG1pbkBvbWljcm9udWF0JnBhc3N3b3JkPUhAU2gxQ29SMyEmc3NsbW9kZT1yZXF1aXJl
  omicron_net_postgress_db_dxp: U2VydmVyPW9taWNyb251YXQucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tO0RhdGFiYXNlPW9taWNyb25fZHhwX3VhdDtQb3J0PTU0MzI7VXNlciBJZD1vbWljcm9uYWRtaW47UGFzc3dvcmQ9SEBTaDFDb1IzITtTc2wgTW9kZT1SZXF1aXJlO1RydXN0IFNlcnZlciBDZXJ0aWZpY2F0ZT10cnVlOw==
  redis: MjAuMjMwLjEwNy4xNDk6NjM3OSxwYXNzd29yZD0xSTROcm1mZE9KRXlmWlRVd1BoWmttc1VobzZrUHlTVzYxN29ublpuckM0PSxhYm9ydENvbm5lY3Q9RmFsc2U=
  eventhub_net_connection: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9aW5zZXJ0YWxvZ3BvbGljeTtTaGFyZWRBY2Nlc3NLZXk9ZEZQTmNrMkJEVTRBQ3g0MkU5SkZ0WDYxVnNkOVZweVJaQmNQK2N4cXY5TT07RW50aXR5UGF0aD1pbnNlcnRsb2dz
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1NYXlvMjAyNDt1c2VyIGlkPUF4aXR5VXNlclByb2Q7cGFzc3dvcmQ9QXh5MjAxM1I7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7TWF4IFBvb2wgU2l6ZT0xMDA7Q29ubmVjdGlvbiBUaW1lb3V0PTkwO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU7
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: TWF5bzIwMjQ=
  keycloak_api_url: aHR0cHM6Ly9vbWljcm9uYXV0aHVhdC5henVyZXdlYnNpdGVzLm5ldC9hdXRoLw==
  keycloak_api_pwd: QXhpdHkyMDIx
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTA0L1NhcEZpbGUv
  oxxopay_private_api_key: a2V5X295RXhoZ25tYjlUTFRiRGN1anV5ZGVO
  oxxopay_public_api_key: a2V5X0hmR0EwR0p3UW5xMFQ0YXFYVWMyRGlU
  professional_license_sep_url: aHR0cHM6Ly93d3cuY2VkdWxhcHJvZmVzaW9uYWwuc2VwLmdvYi5teC8=
  kafka_eh_fqdn: b21pY3JvbmxhYnVhdG5zcC5zZXJ2aWNlYnVzLndpbmRvd3MubmV0OjkwOTM=
  kafka_processexternalorders_eh_name: cHJvY2Vzc2V4dGVybmFsb3JkZXJz
  kafka_processexternalorders_consumer_group: cHJvY2Vzc2V4dGVybmFsb3JkZXJz
  kafka_processexternalorders_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9cHJvY2Vzc2V4dGVybmFsb3JkZXJzcG9saWN5O1NoYXJlZEFjY2Vzc0tleT1DanlQNlNPUnRkNjV2Z2NvSUV2SFBJUTZNUkRmMU5yYU8rQUVoTm9ORHhFPTtFbnRpdHlQYXRoPXByb2Nlc3NleHRlcm5hbG9yZGVycw==
  kafka_sendresponsewebhook_eh_name: c2VuZHJlc3BvbnNld2ViaG9vaw==
  kafka_sendresponsewebhook_consumer_group: c2VuZHJlc3BvbnNld2ViaG9vaw==
  kafka_sendresponsewebhook_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9c2VuZHJlc3BvbnNld2ViaG9va3BvbGljeTtTaGFyZWRBY2Nlc3NLZXk9bS8rRGFTa2tCbzFlNDY2MC8zbGNuU1JCYXVPWHNwUU0zK0FFaEIxTWtvRT07RW50aXR5UGF0aD1zZW5kcmVzcG9uc2V3ZWJob29r
  azure_auth_mode: c2VydmljZXByaW5jaXBhbA==
  azure_authority_url: aHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL29yZ2FuaXphdGlvbnMv
  azure_client_id: NTJkYTVkN2UtOTk4Yy00ZTNlLWE3MTktZjdiNzgxYzA3NTJk
  azure_tenant_id: ODZkZjE3YTUtZDNkNS00YmQyLTg1NTMtN2IwZDU3YTNiNzNj
  azure_scope_base: aHR0cHM6Ly9hbmFseXNpcy53aW5kb3dzLm5ldC9wb3dlcmJpL2FwaS8uZGVmYXVsdA==
  azure_client_secret: M1VUOFF+Y2QzOXN2WUlDYXoyYX5RUXc0M2RwVHNfdF9lbnJ0TGE3Yw==
  power_bi_url: aHR0cHM6Ly9hcGkucG93ZXJiaS5jb20=
  power_bi_workspace_id: NjJhZDczOWYtZGZhNy00MWYwLWIwOWMtMzc3ZGNmNTA4Yzkx
  power_bi_business_analysis_report_id: MGIwMTUzNDgtZTc4NS00ZDdiLTkwMDQtZjQ1NjE2ZTZmNTMy
  power_bi_business_potential_report_id: OGM0NjgyN2UtMTdkZi00Zjk0LWFlMDgtZTA3Zjc5MjIzYWQy
  eventhub_net_connection_finalizeproductionordersap: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9ZmluYWxpemVwcm9kdWN0aW9ub3JkZXJzYXBwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PUI4NmJGbktxWDlOU1hyNzZXTXpONG16SlFyZlZyTDZXVytBRWhCOVczMTQ9O0VudGl0eVBhdGg9ZmluYWxpemVwcm9kdWN0aW9ub3JkZXJzYXB1YXQ=
  eventhub_net_connection_finalizeproductionorderpostgresql: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwMi5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPWZpbmFsaXplcHJvZHVjdGlvbm9yZGVycG9zdGdyZXNxbHVhdHBvbGljeTtTaGFyZWRBY2Nlc3NLZXk9SUdZTWpxd1dmK2R1QW00OTlWalYyODRHWkJhd2Z3ak9iK0FFaEFOTy8vUT07RW50aXR5UGF0aD1maW5hbGl6ZXByb2R1Y3Rpb25vcmRlcnBvc3RncmVzcWx1YXQ=
  eventhub_net_connection_productionorderpdfgeneration: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwMi5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPXByb2R1Y3Rpb25vcmRlcnBkZmdlbmVyYXRpb251YXRwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PUpFbis5SHRJeVM3VVcyaHdXYXBUamFVWDVyb1UwdnJYSytBRWhCQVppZ0E9O0VudGl0eVBhdGg9cHJvZHVjdGlvbm9yZGVycGRmZ2VuZXJhdGlvbnVhdA==
