apiVersion: v1
kind: Secret
metadata:
  name: omicron-uat
data:
  omicron_net_postgress_db: U2VydmVyPW9taWNyb251YXQucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tO1BvcnQ9NTQzMjtVaWQ9b21pY3JvbmFkbWluQG9taWNyb251YXQ7UHdkPUhAU2gxQ29SMyE7RGF0YWJhc2U9b21pY3Jvbl91YXQ7VHJ1c3QgU2VydmVyIENlcnRpZmljYXRlPXRydWU7UG9vbGluZz10cnVlO01pblBvb2xTaXplPTE7TWF4UG9vbFNpemU9MTAwO1RpbWVvdXQ9MTA7U3NsTW9kZT1SZXF1aXJl
  omicron_jdbc_postgress_db: amRiYzpwb3N0Z3Jlc3FsOi8vb21pY3JvbnVhdC5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9vbWljcm9uX3VhdD91c2VyPW9taWNyb25hZG1pbkBvbWljcm9udWF0JnBhc3N3b3JkPUhAU2gxQ29SMyEmc3NsbW9kZT1yZXF1aXJl
  omicron_net_postgress_db_dxp: U2VydmVyPW9taWNyb251YXQucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tO1BvcnQ9NTQzMjtVaWQ9b21pY3JvbmFkbWluQG9taWNyb251YXQ7UHdkPUhAU2gxQ29SMyE7RGF0YWJhc2U9b21pY3Jvbl9keHBfdWF0O1RydXN0IFNlcnZlciBDZXJ0aWZpY2F0ZT10cnVlO1Bvb2xpbmc9dHJ1ZTtNaW5Qb29sU2l6ZT0xO01heFBvb2xTaXplPTEwMDtUaW1lb3V0PTEwO1NzbE1vZGU9UmVxdWlyZQ==
  redis: MjAuMjMwLjEwNy4xNDk6NjM3OSxwYXNzd29yZD0xSTROcm1mZE9KRXlmWlRVd1BoWmttc1VobzZrUHlTVzYxN29ublpuckM0PSxhYm9ydENvbm5lY3Q9RmFsc2U=
  eventhub_net_connection: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9aW5zZXJ0YWxvZ3BvbGljeTtTaGFyZWRBY2Nlc3NLZXk9ZEZQTmNrMkJEVTRBQ3g0MkU5SkZ0WDYxVnNkOVZweVJaQmNQK2N4cXY5TT07RW50aXR5UGF0aD1pbnNlcnRsb2dz
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1NYXlvMjAyNDt1c2VyIGlkPUF4aXR5VXNlclByb2Q7cGFzc3dvcmQ9QXh5MjAxM1I7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7TWF4IFBvb2wgU2l6ZT0xMDA7Q29ubmVjdGlvbiBUaW1lb3V0PTkwOw==
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: TWF5bzIwMjQ=
  keycloak_api_url: aHR0cHM6Ly9vbWljcm9uYXV0aHVhdC5henVyZXdlYnNpdGVzLm5ldC9hdXRoLw==
  keycloak_api_pwd: QXhpdHkyMDIx
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTA0L1NhcEZpbGUv
