apiVersion: v1
kind: Secret
metadata:
  name: omicron-uat
data:
  omicron_net_postgress_db: U2VydmVyPW9taWNyb251YXQucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tO0RhdGFiYXNlPW9taWNyb25fdWF0O1BvcnQ9NTQzMjtVc2VyIElkPW9taWNyb25hZG1pbjtQYXNzd29yZD1IQFNoMUNvUjMhO1NzbCBNb2RlPVJlcXVpcmU7VHJ1c3QgU2VydmVyIENlcnRpZmljYXRlPXRydWU7
  omicron_jdbc_postgress_db: amRiYzpwb3N0Z3Jlc3FsOi8vb21pY3JvbnVhdC5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb206NTQzMi9vbWljcm9uX3VhdD91c2VyPW9taWNyb25hZG1pbkBvbWljcm9udWF0JnBhc3N3b3JkPUhAU2gxQ29SMyEmc3NsbW9kZT1yZXF1aXJl
  omicron_net_postgress_db_dxp: U2VydmVyPW9taWNyb251YXQucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tO0RhdGFiYXNlPW9taWNyb25fZHhwX3VhdDtQb3J0PTU0MzI7VXNlciBJZD1vbWljcm9uYWRtaW47UGFzc3dvcmQ9SEBTaDFDb1IzITtTc2wgTW9kZT1SZXF1aXJlO1RydXN0IFNlcnZlciBDZXJ0aWZpY2F0ZT10cnVlOw==
  redis: MjAuMjMwLjEwNy4xNDk6NjM3OSxwYXNzd29yZD0xSTROcm1mZE9KRXlmWlRVd1BoWmttc1VobzZrUHlTVzYxN29ublpuckM0PSxhYm9ydENvbm5lY3Q9RmFsc2U=
  eventhub_net_connection: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9aW5zZXJ0YWxvZ3BvbGljeTtTaGFyZWRBY2Nlc3NLZXk9ZEZQTmNrMkJEVTRBQ3g0MkU5SkZ0WDYxVnNkOVZweVJaQmNQK2N4cXY5TT07RW50aXR5UGF0aD1pbnNlcnRsb2dz
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1NYXlvMjAyNDt1c2VyIGlkPUF4aXR5VXNlclByb2Q7cGFzc3dvcmQ9QXh5MjAxM1I7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7TWF4IFBvb2wgU2l6ZT0xMDA7Q29ubmVjdGlvbiBUaW1lb3V0PTkwOw==
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: TWF5bzIwMjQ=
  keycloak_api_url: aHR0cHM6Ly9vbWljcm9uYXV0aHVhdC5henVyZXdlYnNpdGVzLm5ldC9hdXRoLw==
  keycloak_api_pwd: QXhpdHkyMDIx
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTA0L1NhcEZpbGUv
  oxxopay_private_api_key: a2V5X295RXhoZ25tYjlUTFRiRGN1anV5ZGVO
  oxxopay_public_api_key: a2V5X0hmR0EwR0p3UW5xMFQ0YXFYVWMyRGlU
  professional_license_sep_url: aHR0cHM6Ly93d3cuY2VkdWxhcHJvZmVzaW9uYWwuc2VwLmdvYi5teC8=
  kafka_processexternalorders_eh_name: cHJvY2Vzc2V4dGVybmFsb3JkZXJz
  kafka_processexternalorders_consumer_group: cHJvY2Vzc2V4dGVybmFsb3JkZXJz
  kafka_processexternalorders_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9cHJvY2Vzc2V4dGVybmFsb3JkZXJzcG9saWN5O1NoYXJlZEFjY2Vzc0tleT1DanlQNlNPUnRkNjV2Z2NvSUV2SFBJUTZNUkRmMU5yYU8rQUVoTm9ORHhFPTtFbnRpdHlQYXRoPXByb2Nlc3NleHRlcm5hbG9yZGVycw==
  kafka_sendresponsewebhook_eh_name: c2VuZHJlc3BvbnNld2ViaG9vaw==
  kafka_sendresponsewebhook_consumer_group: c2VuZHJlc3BvbnNld2ViaG9vaw==
  kafka_sendresponsewebhook_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFidWF0bnNwLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9c2VuZHJlc3BvbnNld2ViaG9va3BvbGljeTtTaGFyZWRBY2Nlc3NLZXk9bS8rRGFTa2tCbzFlNDY2MC8zbGNuU1JCYXVPWHNwUU0zK0FFaEIxTWtvRT07RW50aXR5UGF0aD1zZW5kcmVzcG9uc2V3ZWJob29r