spring:
  application:
    name: eureka-service
  profiles: dev

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

keycloak:
  enabled: true
  auth-server-url: https://devtools.axity.com/auth
  use-resource-role-mappings: true
  public-client: true
  cors: true
  realm: omicron
  resource: omicron-dxp
  securityConstraints:
    - authRoles: [doctor]
      securityCollections:
        - name: doctor-dxp
          patterns: [/api/dxp/*]
    - authRoles: [advisor]
      securityCollections:
        - name: advisor-dxp
          patterns: [/api/dxp/*]
    - authRoles: []
      securityCollections:
        - name: public-dxp
          patterns: [/api/dxp/payments/public/*]
  ssl-required: external

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauth-service
    catalogos:
      path: /catalogos/**
      serviceId: catalogosservice
    usuarios:
      path: /usuarios/**
      serviceId: usuariosservice
    sapadapter:
      path: /sapadapter/**
      serviceId: sapadapterService
    pedidos:
      path: /pedidos/**
      serviceId: pedidosservice
    warehouses:
      path: /warehouses/**
      serviceId: warehousesservice
    reporting:
      path: /reporting/**
      serviceId: reportingservice
    almacen:
      path: /almacen/**
      serviceId: almacenservice
    dxp:
      path: /dxp/mock/**
      url: https://reqres.in/api/ #mock endpoint, agregar serviceId de eureka
    dxp-public:
      path: /dxp/public/mock/**
      url: https://reqres.in/api/ #mock endpoint, agregar serviceId de eureka
    dxp-favorites:
      path: /dxp/favorites/**
      serviceId: favoritiesservice
    dxp-sapordersadapter:
      path: /dxp/sapordersadapter/**
      serviceId: sapordersadapterservice
    dxp-shoppingcart:
      path: /dxp/shoppingcart/**
      serviceId: shoppingcartservice
    dxp-catalog:
      path: /dxp/catalog/**
      serviceId: catalogsdxpservice
    dxp-advisor:
      path: /dxp/advisor/**
      serviceId: advisorservice
    dxp-notifications:
      path: /dxp/notifications/**
      serviceId: notificationsservice
    dxp-doctors:
      path: /dxp/doctors/**
      serviceId: doctorservice
    dxp-files:
      path: /dxp/files/**
      serviceId: filesservice
    dxp-processpayments:
      path: /dxp/processpayments/**
      serviceId: processpaymentservice
    dxp-payments:
      path: /dxp/payments/**
      serviceId: paymentsservice
    dxp-pedidosdxp:
      path: /dxp/pedidosdxp/**
      serviceId: pedidosdxpservice
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  semaphore.maxSemaphores: 30000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 3000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  MaxTotalHttpConnections: 7000
  MaxConnectionsPerHost: 1000
