spring:
  application:
    name: eureka-service
  profiles: qa

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

keycloak:
  enabled: true
  auth-server-url: https://http://201.163.179.28:9090/
  use-resource-role-mappings: true
  public-client: true
  cors: true
  realm: omicron
  resource: omicron-dxp
  securityConstraints:
    - authRoles:
        - external-dxp
      securityCollections:
        - name: protected-dxp
          patterns:
            - /api/dxp/*
  ssl-required: external
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauth-service
    catalogos:
      path: /catalogos/**
      serviceId: catalogosservice
    usuarios:
      path: /usuarios/**
      serviceId: usuariosservice
    sapadapter:
      path: /sapadapter/**
      serviceId: sapadapterService
    pedidos:
      path: /pedidos/**
      serviceId: pedidosservice
    warehouses:
      path: /warehouses/**
      serviceId: warehousesservice
    reporting:
      path: /reporting/**
      serviceId: reportingservice
    almacen:
      path: /almacen/**
      serviceId: almacenservice
    dxp:
      path: /dxp/mock/**
      url: https://reqres.in/api/ #mock endpoint, agregar serviceId de eureka
    dxp-favorites:
      path: /dxp/favorites/**
      serviceId: favoritiesservice
    dxp-sapordersadapter:
      path: /dxp/sapordersadapter/**
      serviceId: sapordersadapterservice
    dxp-shoppingcart:
      path: /dxp/shoppingcart/**
      serviceId: shoppingcartservice
    dxp-catalog:
      path: /dxp/catalog/**
      serviceId: catalogsdxpservice
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  semaphore.maxSemaphores: 30000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 3000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  MaxTotalHttpConnections: 7000
  MaxConnectionsPerHost: 1000
