spring:
  application:
    name: eureka-service
  profiles: prod

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauth-service
    catalogos:
      path: /catalogos/**
      serviceId: catalogosservice
    usuarios:
      path: /usuarios/**
      serviceId: usuariosservice
    sapadapter:
      path: /sapadapter/**
      serviceId: sapadapterService
    pedidos:
      path: /pedidos/**
      serviceId: pedidosservice
    warehouses:
      path: /warehouses/**
      serviceId: warehousesservice
    reporting:
      path: /reporting/**
      serviceId: reportingservice
    almacen:
      path: /almacen/**
      serviceId: almacenservice
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  semaphore.maxSemaphores: 30000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 60000
  ConnectionTimeout: 3000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  MaxTotalHttpConnections: 7000
  MaxConnectionsPerHost: 1000
