spring:
  application:
    name: eureka-service

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    oauth:
      path: /oauth/**
      serviceId: oauth-service
    catalogos:
      path: /catalogos/**
      serviceId: catalogosservice
    usuarios:
      path: /usuarios/**
      serviceId: usuariosservice
    sapadapter:
      path: /sapadapter/**
      serviceId: sapadapterService
    pedidos:
      path: /pedidos/**
      serviceId: pedidosservice
    warehouses:
      path: /warehouses/**
      serviceId: warehousesservice
    reporting:
      path: /reporting/**
      serviceId: reportingservice
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000

oauth:
  ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 3000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    MaxTotalHttpConnections: 7000
    MaxConnectionsPerHost: 1000
catalogos:
  ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 3000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    MaxTotalHttpConnections: 7000
    MaxConnectionsPerHost: 1000
usuarios:
  ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 3000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    MaxTotalHttpConnections: 7000
    MaxConnectionsPerHost: 1000
sapadapter:
  ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 3000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    MaxTotalHttpConnections: 7000
    MaxConnectionsPerHost: 1000
pedidos:
  ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 3000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    MaxTotalHttpConnections: 7000
    MaxConnectionsPerHost: 1000
warehouses:
  ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 3000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    MaxTotalHttpConnections: 7000
    MaxConnectionsPerHost: 1000
reporting:
  ribbon:
    ReadTimeout: 60000
    ConnectionTimeout: 3000
    MaxAutoRetries: 2
    MaxAutoRetriesNextServer: 2
    MaxTotalHttpConnections: 7000
    MaxConnectionsPerHost: 1000