apiVersion: v1
kind: Secret
metadata:
  name: omicron-dev
data:
  omicron_net_postgress_db: U2VydmVyPTE5Mi4xNjguMC4xMDE7UG9ydD01NDMyO1VpZD1vbWljcm9udXNlcjtQd2Q9QXhpdHkyMDIwO0RhdGFiYXNlPW9taWNyb25kZXY=
  omicron_net_postgress_db_dxp: U2VydmVyPTE5Mi4xNjguMC4xMDE7UG9ydD01NDM0O1VpZD1vbWljcm9uO1B3ZD1BeGl0eTIwMjA7RGF0YWJhc2U9b21pY3JvbmR4cF9kZXY=
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1CQ1BfT21pY3JvbmxhYl8xOTA0MjAyMjt1c2VyIGlkPUF4aXR5VXNlclFBO3Bhc3N3b3JkPUZzajRyMTcwTXE7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7Q29ubmVjdGlvbiBUaW1lb3V0PTU7
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: QkNQX09taWNyb25sYWJfMTkwNDIwMjI=
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTAzL1NhcEZpbGUv
  seqlog_svc_service_host_name: MTkyLjE2OC4wLjEwMQ==
  oxxopay_private_api_key: a2V5X295RXhoZ25tYjlUTFRiRGN1anV5ZGVO
  oxxopay_public_api_key: a2V5X0hmR0EwR0p3UW5xMFQ0YXFYVWMyRGlU
  professional_license_sep_url: aHR0cHM6Ly93d3cuY2VkdWxhcHJvZmVzaW9uYWwuc2VwLmdvYi5teC8=
  azure_auth_mode: c2VydmljZXByaW5jaXBhbA==
  azure_authority_url: aHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL29yZ2FuaXphdGlvbnMv
  azure_client_id: NTJkYTVkN2UtOTk4Yy00ZTNlLWE3MTktZjdiNzgxYzA3NTJk
  azure_tenant_id: ODZkZjE3YTUtZDNkNS00YmQyLTg1NTMtN2IwZDU3YTNiNzNj
  azure_scope_base: aHR0cHM6Ly9hbmFseXNpcy53aW5kb3dzLm5ldC9wb3dlcmJpL2FwaS8uZGVmYXVsdA==
  azure_client_secret: M1VUOFF+Y2QzOXN2WUlDYXoyYX5RUXc0M2RwVHNfdF9lbnJ0TGE3Yw==
  power_bi_url: aHR0cHM6Ly9hcGkucG93ZXJiaS5jb20=
  power_bi_workspace_id: NjJhZDczOWYtZGZhNy00MWYwLWIwOWMtMzc3ZGNmNTA4Yzkx
  power_bi_business_analysis_report_id: MGIwMTUzNDgtZTc4NS00ZDdiLTkwMDQtZjQ1NjE2ZTZmNTMy
  power_bi_business_potential_report_id: OGM0NjgyN2UtMTdkZi00Zjk0LWFlMDgtZTA3Zjc5MjIzYWQy