apiVersion: v1
kind: Secret
metadata:
  name: omicron-dev
data:
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: QkNQX09taWNyb25sYWJfMTkwNDIwMjI=
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTAzL1NhcEZpbGUv
