spring:
  datasource:
    url: ${POSTGRESS_JDBC_CONNECTION_STRING}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 1000
      minimumIdle: 3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: oauth-service
  profiles: uat

server:
  port: 8090

security:
  values:
    secret: Prueba
    ttl: 3600000
    ttl-refresh: 604800
