spring:
  datasource:
    #url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:postgresql://192.168.0.101:5432/omicrondev
    username: omicronuser
    password: Axity2020
    driver-class-name: org.postgresql.Driver
  #datasource:
    #url: jdbc:sqlserver://localhost;databaseName=securitydb
    #username: sa
    #password: Axity&2019Arq
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: oauth-service
  profiles:
    active: dev

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.101:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

security:
    values:
      secret: Prueba
      ttl: 3600
      ttl-refresh: 604800