spring:
  datasource:
    url: jdbc:postgresql://omicron.postgres.database.azure.com:5432/omicronprod?user=omicronadmin@omicron&password=e0F6gH4CfrBeZdiO.2020&sslmode=require
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: oauth-service
  profiles: prod

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.83:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

security:
    values:
      secret: Prueba
      ttl: 3600
      ttl-refresh: 604800