spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=securitydb
    username: sa
    password: Axity&2019Arq
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
  application:
    name: oauth-service
  profiles:
    active: dev

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true

security:
    values:
      secret: Prueba
      ttl: 3600
