spring:
  datasource:
    #url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:postgresql://127.0.0.1:5432/omicron
    username: omicronapp
    password: 5a677Gykn-Tx
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 1000
      minimumIdle: 3
    #datasource:
    #url: jdbc:sqlserver://localhost;databaseName=securitydb
    #username: sa
    #password: Axity&2019Arq
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  application:
    name: oauth-service
  profiles: qa

server:
  port: 8090

security:
  values:
    secret: Prueba
    ttl: 3600000
    ttl-refresh: 604800
