apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthserver-deployment
  labels:
    app: oauthserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oauthserver
  template:
    metadata:
      labels:
        app: oauthserver
    spec:
      containers:
        - name: oauthserver
          image: omicron.azurecr.io/omicronprod/omicron-appiosformulas-oauthserver-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: POSTGRESS_JDBC_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_jdbc_postgress_db
          ports:
            - containerPort: 8090
          resources:
            limits:
              cpu: 500m
              memory: 900Mi
            requests:
              cpu: 300m
              memory: 630Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: oauthserver-svc
  labels:
    app: oauthserver
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8090
  selector:
    app: oauthserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogos-deployment
  labels:
    app: catalogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogos
  template:
    metadata:
      labels:
        app: catalogos
    spec:
      containers:
        - name: catalogos
          image: omicron.azurecr.io/omicronprod/omicron-appiosformulas-catalogos-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
            - name: ELASTIC_APM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_token
            - name: ELASTIC_APM_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_url
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 220m
              memory: 210Mi
            requests:
              cpu: 154m
              memory: 147Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: catalogos-svc
  labels:
    app: catalogos
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: catalogos
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-deployment
  labels:
    app: usuarios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuarios
  template:
    metadata:
      labels:
        app: usuarios
    spec:
      containers:
        - name: usuarios
          image: omicron.azurecr.io/omicronprod/omicron-appiosformulas-usuarios-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
            - name: ELASTIC_APM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_token
            - name: ELASTIC_APM_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_url
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 215m
              memory: 370Mi
            requests:
              cpu: 151m
              memory: 259Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: usuarios-svc
  labels:
    app: usuarios
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: usuarios
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapadapter-deployment
  labels:
    app: sapadapter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sapadapter
  template:
    metadata:
      labels:
        app: sapadapter
    spec:
      containers:
        - name: sapadapter
          image: omicron.azurecr.io/omicronprod/omicron-appiosformulas-sapadapter-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: redis
            - name: SAP_CONNECTION_STRING_SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: sap_connection_string_sql_server
            - name: OMICRON_FILE_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_file_url
            - name: ELASTIC_APM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_token
            - name: ELASTIC_APM_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_url
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 350m
              memory: 350Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: sapadapter-svc
  labels:
    app: sapadapter
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: sapadapter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-deployment
  labels:
    app: pedidos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
        - name: pedidos
          image: omicron.azurecr.io/omicronprod/omicron-appiosformulas-pedidos-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: redis
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
            - name: EVENHUB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: eventhub_net_connection
            - name: SAP_DI_API_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: sap_di_api_url
            - name: SAP_FILE_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: sap_file_url
            - name: OMICRON_FILE_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_file_url
            - name: STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: storage_account
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: storage_account_key
            - name: ELASTIC_APM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_token
            - name: ELASTIC_APM_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_url
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 150m
              memory: 1000Mi
            requests:
              cpu: 105m
              memory: 700Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-svc
  labels:
    app: pedidos
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: pedidos
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouses-deployment
  labels:
    app: warehouses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouses
  template:
    metadata:
      labels:
        app: warehouses
    spec:
      containers:
        - name: warehouses
          image: omicron.azurecr.io/omicronprod/omicron-appiosformulas-warehouses-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: POSTGRESS_NET_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: omicron_net_postgress_db
            - name: ELASTIC_APM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_token
            - name: ELASTIC_APM_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_url
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: redis
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 135m
              memory: 135Mi
            requests:
              cpu: 95m
              memory: 95Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: warehouses-svc
  labels:
    app: warehouses
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: warehouses
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-deployment
  labels:
    app: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
    spec:
      containers:
        - name: reporting
          image: omicron.azurecr.io/omicronprod/omicron-appiosformulas-reporting-repository:latest
          env:
            - name: TZ
              value: America/Mexico_City
            - name: ASPNETCORE_ENVIRONMENT
              value: Prod
            - name: STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: storage_account
            - name: STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: storage_account_key
            - name: ELASTIC_APM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_token
            - name: ELASTIC_APM_URL
              valueFrom:
                secretKeyRef:
                  name: omicron-prod
                  key: elastic_apm_url
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 180Mi
            requests:
              cpu: 70m
              memory: 126Mi
      imagePullSecrets:
        - name: pullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: reporting-svc
  labels:
    app: reporting
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: reporting
  type: ClusterIP
---

