apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-magistrales
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://oauthserver-svc.default.svc.cluster.local/oauthrs/validate"
    nginx.ingress.kubernetes.io/auth-method: "GET"
    #If you need services redirect to login on fail, uncomment this line
    #nginx.ingress.kubernetes.io/auth-signin: "http://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email, authorization"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/auth-snippet: |
      set $auth_header $http_authorization;
spec:
  ingressClassName: nginx-api
  tls:
    - hosts:
        - magistralesprod.omicronlab.com.mx
      secretName: secure-tls-prod-2025
  rules:
    - host: magistralesprod.omicronlab.com.mx
      http:
        paths:
          - backend:
              service:
                name: catalogos-svc
                port:
                  number: 80
            path: /api/catalogos(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: usuarios-svc
                port:
                  number: 80
            path: /api/usuarios(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: sapadapter-svc
                port:
                  number: 80
            path: /api/sapadapter(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: pedidos-svc
                port:
                  number: 80
            path: /api/pedidos(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: warehouses-svc
                port:
                  number: 80
            path: /api/warehouses(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: reporting-svc
                port:
                  number: 80
            path: /api/reporting(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: reporting-svc
                port:
                  number: 80
            path: /api/reporting(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: sapservicelayeradapter-svc
                port:
                  number: 80
            path: /api/sapservicelayeradapter(/|$)(.*)
            pathType: Prefix
