---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Resetting kubeadm
    shell: kubeadm reset -f
    register: output

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --node-name {{node_name}} --pod-network-cidr={{ cidr_v }}
    register: output

  - name: Print kubeadm token
    debug:
      var: output.stdout

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  
  - name: Enable master as node
    shell: |
     kubectl taint nodes {{ node_name }} node-role.kubernetes.io/master-