---
- name: Install Jenkins plugins
  hosts: all
  become: yes
  tasks:
    - name: Install NodeJs 
      jenkins_plugin:
        name: nodejs
        state: latest
        url_username: admin
        url_password: admin123
        url: http://{{ ansible_host }}:8080

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted