apiVersion: v1
kind: Secret
metadata:
  name: omicron-qa
data:
  omicron_net_postgress_db: U2VydmVyPTE5Mi4xNjguMC44MztQb3J0PTU0MzI7VWlkPW9taWNyb251c2VyO1B3ZD1BeGl0eTIwMjA7RGF0YWJhc2U9b21pY3JvbmRldg==
  omicron_net_postgress_db_dxp: U2VydmVyPTE5Mi4xNjguMC44MztQb3J0PTU0MzQ7VWlkPW9taWNyb247UHdkPUF4aXR5MjAyMDtEYXRhYmFzZT1vbWljcm9uZHhwX2Rldg==
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1CQ1BfT21pY3JvbmxhYl8xOTA0MjAyMjt1c2VyIGlkPUF4aXR5VXNlclByb2Q7cGFzc3dvcmQ9QXh5MjAxM1I7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7Q29ubmVjdGlvbiBUaW1lb3V0PTU7
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: QkNQX09taWNyb25sYWJfMTkwNDIwMjI=
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTAzL1NhcEZpbGUv
  redis_connection_string: aHR0cDovL3JlZGlzLXN2Yy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsLyxwYXNzd29yZD1hV3RMTmpZNFdDNDJPbXRXLGFib3J0Q29ubmVjdD1GYWxzZQ==
  elastic_url: aHR0cDovLzE5Mi4xNjguMC44Mzo5MjAwLw==
  kafka_eh_fqdn: b21pY3JvbmxhYnByb2Ruc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldDo5MDkz
  kafka_report_eh_name: cmVwb3J0cWE=
  kafka_report_consumer_group: cmVwb3J0cWE=
  kafka_report_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1yZXBvcnRwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PUF1dnNEc0JuVWNZZE1pd1JSU3prS2sxVFhFK3RQMFVVc2xQYm44OTNMY3M9O0VudGl0eVBhdGg9cmVwb3J0cWE=
  kafka_creditpayment_eh_name: Y3JlZGl0cGF5bWVudHFh
  kafka_creditpayment_consumer_group: Y3JlZGl0cGF5bWVudHFh
  kafka_creditpayment_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1jcmVkaXRwYXltZW50cWFwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PTh1UU85MHBQdVR0TG4vMXhKUEp3aWFTOUtFbkhCaWsrYU5JdmdUSlgvdFU9O0VudGl0eVBhdGg9Y3JlZGl0cGF5bWVudHFhMXhKUEp3aWFTOUtFbkhCaWsrYU5JdmdUSlgvdFU9O0VudGl0eVBhdGg9Y3JlZGl0cGF5bWVudHFh
  kafka_paypalpayment_eh_name: cGF5cGFscGF5bWVudHFh
  kafka_paypalpayment_consumer_group: cGF5cGFscGF5bWVudHFh
  kafka_paypalpayment_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1wYXlwYWxwYXltZW50cG9saWN5O1NoYXJlZEFjY2Vzc0tleT1xVThrcWRyY1UrMTZ1N3JNUERRQkphdGE1cFJoSjgxc2ZnRTB1RmJIcUZnPTtFbnRpdHlQYXRoPXBheXBhbHBheW1lbnRxYQ==
  kafka_bbvapayment_eh_name: YmJ2YXBheW1lbnRxYQ==
  kafka_bbvapayment_consumer_group: YmJ2YXBheW1lbnRxYQ==
  kafka_bbvapayment_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1iYnZhcGF5bWVudHBvbGljeTtTaGFyZWRBY2Nlc3NLZXk9d0Q0OWFDeWtqdTlIbjJBV1pPRDlHa2N6cGI5Uy8xZ2dqdU1zcmtkYzhxUT07RW50aXR5UGF0aD1iYnZhcGF5bWVudHFh
  kafka_validationorder_eh_name: dmFsaWRhdGlvbm9yZGVycWE=
  kafka_validationorder_consumer_group: dmFsaWRhdGlvbm9yZGVycWE=
  kafka_validationorder_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT12YWxpZGF0aW9ub3JkZXJwb2xpY3k7U2hhcmVkQWNjZXNzS2V5PW90cG1UUStmU2dndnhSVXZ0YUJVRTE3bThNS2xKTjlnTStBRWhPaUcxT2c9O0VudGl0eVBhdGg9dmFsaWRhdGlvbm9yZGVycWE=
  kafka_promotionalemails_eh_name: cHJvbW90aW9uYWxlbWFpbHNxYQ==
  kafka_promotionalemails_consumer_group: cHJvbW90aW9uYWxlbWFpbHNxYQ==
  kafka_promotionalemails_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1wcm9tb3Rpb25hbGVtYWlsc3FhcG9saWN5O1NoYXJlZEFjY2Vzc0tleT1vcldheXhlYk9LbUZqbTNwWERXMEtlTzhDOVEwYndHVlhFL2NRSUpBNUdNPTtFbnRpdHlQYXRoPXByb21vdGlvbmFsZW1haWxzcWE=
  kafka_promotionalemailsresend_eh_name: cHJvbW90aW9uYWxlbWFpbHNyZXNlbmRxYQ==
  kafka_promotionalemailsresend_consumer_group: cHJvbW90aW9uYWxlbWFpbHNyZXNlbmRxYQ==
  kafka_promotionalemailsresend_eh_connection_string: RW5kcG9pbnQ9c2I6Ly9vbWljcm9ubGFicWFuc3Auc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1wcm9tb3Rpb25hbGVtYWlsc3Jlc2VuZHFhcG9saWN5O1NoYXJlZEFjY2Vzc0tleT1MSFV1Vk5VRlZjVmFEMjFjeHdGQzU5Z3FmVUMxMTFMd0I2T1gvbVNEZW13PTtFbnRpdHlQYXRoPXByb21vdGlvbmFsZW1haWxzcmVzZW5kcWE=
  kafka_insertlogs_eh_name: aW5zZXJ0bG9ncw==
  oxxopay_private_api_key: a2V5X295RXhoZ25tYjlUTFRiRGN1anV5ZGVO
  oxxopay_public_api_key: a2V5X0hmR0EwR0p3UW5xMFQ0YXFYVWMyRGlU
  professional_license_sep_url: aHR0cHM6Ly93d3cuY2VkdWxhcHJvZmVzaW9uYWwuc2VwLmdvYi5teC8=
  azure_auth_mode: c2VydmljZXByaW5jaXBhbA==
  azure_authority_url: aHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL29yZ2FuaXphdGlvbnMv
  azure_client_id: NTJkYTVkN2UtOTk4Yy00ZTNlLWE3MTktZjdiNzgxYzA3NTJk
  azure_tenant_id: ODZkZjE3YTUtZDNkNS00YmQyLTg1NTMtN2IwZDU3YTNiNzNj
  azure_scope_base: aHR0cHM6Ly9hbmFseXNpcy53aW5kb3dzLm5ldC9wb3dlcmJpL2FwaS8uZGVmYXVsdA==
  azure_client_secret: M1VUOFF+Y2QzOXN2WUlDYXoyYX5RUXc0M2RwVHNfdF9lbnJ0TGE3Yw==
  power_bi_url: aHR0cHM6Ly9hcGkucG93ZXJiaS5jb20=
  power_bi_workspace_id: NjJhZDczOWYtZGZhNy00MWYwLWIwOWMtMzc3ZGNmNTA4Yzkx
  power_bi_business_analysis_report_id: MGIwMTUzNDgtZTc4NS00ZDdiLTkwMDQtZjQ1NjE2ZTZmNTMy
  power_bi_business_potential_report_id: OGM0NjgyN2UtMTdkZi00Zjk0LWFlMDgtZTA3Zjc5MjIzYWQy

