apiVersion: v1
kind: Secret
metadata:
  name: omicron-qa
data:
  omicron_net_postgress_db: U2VydmVyPTE5Mi4xNjguMC44MztQb3J0PTU0MzI7VWlkPW9taWNyb251c2VyO1B3ZD1BeGl0eTIwMjA7RGF0YWJhc2U9b21pY3JvbmRldg==
  omicron_net_postgress_db_dxp: U2VydmVyPTE5Mi4xNjguMC44MztQb3J0PTU0MzQ7VWlkPW9taWNyb247UHdkPUF4aXR5MjAyMDtEYXRhYmFzZT1vbWljcm9uZHhwX2Rldg==
  sap_connection_string_sql_server: U2VydmVyPTE3Mi4zMS41NS4xNjtEYXRhYmFzZT1CQ1BfT21pY3JvbmxhYl8xOTA0MjAyMjt1c2VyIGlkPUF4aXR5VXNlclByb2Q7cGFzc3dvcmQ9QXh5MjAxM1I7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPVRydWU7Q29ubmVjdGlvbiBUaW1lb3V0PTU7
  sap_service_layer_url: aHR0cHM6Ly8xNzIuMzEuNTUuMTE6NTAwMDAvYjFzL3YxLw==
  sap_service_layer_user: bWFuYWdlcg==
  sap_service_layer_pwd: MG0xY3Iwbmw0Yg==
  sap_service_layer_db: QkNQX09taWNyb25sYWJfMTkwNDIwMjI=
  sap_file_url: aHR0cDovLzE3Mi4zMS41NS4xMTo1MTAzL1NhcEZpbGUv