name: omicron-magistrales-sonar
on:
  workflow_dispatch:
    inputs:
      force_test:
        description: Force Test
        type: boolean
        default: false
        required: false
  pull_request:
    branches:
      - develop
      - release/qa
    paths:
      - frontend/**
      - services/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Test frontend/web
        if: ${{ (contains(steps.changeset.outputs.changes, 'frontend/web')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-web
        with:
          path: frontend/web
          project_name: web
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Test catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/catalogos-service
          project_name: Catalogos
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Test pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/pedidos-service
          project_name: Pedidos
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          net_version: 6.0.x

      - name: Test reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/reporting-service
          project_name: Reporting
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Test sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/sapadapter-service
          project_name: SapAdapter
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Test usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/usuarios-service
          project_name: Usuarios
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Test warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/warehouses-service
          project_name: Warehouses
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Test sapservicelayeradapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net-v2
        with:
          path: services/sapservicelayeradapter-service
          project_name: SapServiceLayerAdapter
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}
          net_version: 6.0.x
