name: omicron-magistrales-qa-aws
on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Force Build
        type: boolean
        default: false
        required: false
  push:
    branches:
      - release/qa
    paths:
      - frontend/**
      - services/**
      - database/**

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: "us-east-2" # us-east-2 US East (Ohio) us-east-1" # US East (N. Viginia)
  AMI_ID: ami-0a68049ee64ac0782
  SUBNET_ID: subnet-073b7bac3af8d3c53
  SECURITY_GROUP_ID: sg-09c9844682ec712ca
  VOLUME_SIZE_GiB: "20"

jobs:
  start-runner:
    timeout-minutes: 5
    name: Start self-hosted EC2 runner
    runs-on: omicron-bastion
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::891376991292:role/GithubActionsRole"
          output-credentials: true

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: Axitymx/ec2-action-builder@main
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ env.AWS_REGION }}
          ec2_instance_type: "t3.medium"
          ec2_ami_id: ${{ env.AMI_ID }}
          ec2_subnet_id: ${{ env.SUBNET_ID }}
          ec2_security_group_id: ${{ env.SECURITY_GROUP_ID }}
          ec2_root_disk_size_gb: ${{ env.VOLUME_SIZE_GiB }}
          ec2_spot_instance_strategy: "BestEffort" # Other options are: SpotOnly, BestEffort, MaxPerformance
          manual_stop: true

  db:
    name: Deploy DB
    needs:
      - start-runner
    runs-on: ${{ github.run_id }}
    environment: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: |
          echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Create Bastion SSH Tunnel
        if: ${{ (contains(steps.changeset.outputs.changes, 'database')) || (inputs.force_build) }}
        uses: ./.github/actions/bastion
        with:
          bastion_pem: ${{ secrets.BASTION_PEM }}
          ec2_user: ${{ secrets.AWS_EC2_USER }}
          bastion_host: ${{ secrets.AWS_BASTION_HOST }}
          db_host: ${{ secrets.AWS_DATABASE_HOST }}
          db_port: ${{ secrets.AWS_DATABASE_PORT }}

      - name: Update database
        if: ${{ (contains(steps.changeset.outputs.changes, 'database')) || (inputs.force_build) }}
        uses: ./.github/actions/liquibase
        with:
          db_name: ${{ secrets.AWS_DATABASE_NAME }}
          db_username: ${{ secrets.AWS_DATABASE_USER }}
          db_password: ${{ secrets.AWS_DATABASE_PASSWORD }}

  build:
    name: Deploy AWS
    needs:
      - start-runner
      - db
    runs-on: ${{ github.run_id }}
    environment: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: |
          echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Set Environments
        uses: ./.github/actions/environments-aws

      - name: Configure AWS credentials Omicron
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Oracle container registry
        run: echo ${{ secrets.ORACLE_PASSWORD }} | docker login container-registry.oracle.com -u ${{ secrets.ORACLE_USERNAME }} --password-stdin
  
      - name: Web
        if: ${{ (contains(steps.changeset.outputs.changes, 'frontend/web')) || (inputs.force_build) }}
        uses: ./.github/actions/deploy-web-aws-s3
        with:
            bucket_name: ${{ secrets.AWS_BUCKET_MAGISTRALES }}
            environment: qa-aws
            working_directory: ./frontend/web
     
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: SET AWS ECR Token
        run: |
          echo "AWS_ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Configure AWS credentials Axity
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AXITY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AXITY_AWS_SECRET_ACCESS_KEY }}

      - name: Get AWS Nuget Token    
        if: ${{ (contains(steps.changeset.outputs.changes, 'services/')) || (inputs.force_build) }}
        run: |
          echo "NUGET_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain axity --domain-owner 992382646884 --region us-east-1 --query authorizationToken --output text)" >> $GITHUB_ENV

      - name: Docker Build an Push Catalogos
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/catalogos-service
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: catalogosmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push OauthServer
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/oauthserver
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: oauthservermagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Pedidos
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/pedidos-service
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: pedidosmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Reporting
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/reporting-service
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: reportingmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push SapAdapter
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/sapadapter-service
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: sapadaptermagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Usuarios
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/usuarios-service
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: usuariosmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Warehouses
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/warehouses-service
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: warehousesmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push SapServiceLayerAdapter
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/sapservicelayeradapter-service
          registry: ${{ env.AWS_ECR_REGISTRY }}
          repository: sapservicelayeradaptermagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}
          aws_nuget_auth_token:  ${{ env.NUGET_AUTH_TOKEN }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_EKS_REGION }}

      - name: Deploy to EKS Magistrales
        working-directory: ./deploy/aws/qa
        run: |
          kubectl apply -f deploy.yml
          kubectl apply -f ingress-services.yml
          kubectl apply -f ingress-oauth.yml
          kubectl apply -f secrets.yml

      - name: Rollout catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy catalogos-deployment

      - name: Rollout oauthserver
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy oauthserver-deployment

      - name: Rollout pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy pedidos-deployment

      - name: Rollout reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy reporting-deployment

      - name: Rollout sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy sapadapter-deployment

      - name: Rollout usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy usuarios-deployment

      - name: Rollout warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy warehouses-deployment

      - name: Rollout sapservicelayeradapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy sapservicelayeradapter-deployment

      - name: Docker prune
        run: |
          docker builder prune -f -a
          docker image prune -f -a

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - db
      - build
    runs-on: omicron-bastion
    permissions:
      actions: write
      contents: read
      id-token: write
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::891376991292:role/GithubActionsRole"
          output-credentials: true

      - name: Stop EC2 runner
        id: stop-ec2-runner
        uses: Axitymx/ec2-action-builder@main
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ env.AWS_REGION }}
          action: "stop"
