name: omicron-magistrales-qa-aws
on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Force Build
        type: boolean
        default: false
        required: false
  push:
    branches:
      - release/qa
    paths:
      - frontend/**
      - services/**
      - database/**
jobs:
  start-runner:
    timeout-minutes: 5
    name: Start self-hosted EC2 runner
    runs-on: [aws-bridge]
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-2"
          role-to-assume: "arn:aws:iam::891376991292:role/GithubActionsRole"
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-08be1e3e6c338b037
          ec2-instance-type: t3.medium
          subnet-id: subnet-073b7bac3af8d3c53
          security-group-id: sg-09c9844682ec712ca
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]

  db:
    name: Deploy DB
    needs:
      - start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    environment: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: |
          echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Create Bastion SSH Tunnel
        if: ${{ (contains(steps.changeset.outputs.changes, 'database')) || (inputs.force_build) }}
        uses: ./.github/actions/bastion
        with:
          bastion_pem: ${{ secrets.BASTION_PEM }}
          ec2_user: ${{ secrets.AWS_EC2_USER }}
          bastion_host: ${{ secrets.AWS_BASTION_HOST }}
          db_host: ${{ secrets.AWS_DATABASE_HOST }}
          db_port: ${{ secrets.AWS_DATABASE_PORT }}

      - name: Update database
        if: ${{ (contains(steps.changeset.outputs.changes, 'database')) || (inputs.force_build) }}
        uses: ./.github/actions/liquibase
        with:
          db_name: ${{ secrets.AWS_DATABASE_NAME }}
          db_username: ${{ secrets.AWS_DATABASE_USER }}
          db_password: ${{ secrets.AWS_DATABASE_PASSWORD }}

  build:
    name: Deploy AWS
    needs:
      - start-runner
      - db
    runs-on: ${{ needs.start-runner.outputs.label }}
    environment: QA
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: |
          echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Oracle container registry
        run: echo ${{ secrets.ORACLE_PASSWORD }} | docker login container-registry.oracle.com -u ${{ secrets.ORACLE_USERNAME }} --password-stdin

      - name: Web
        if: ${{ (contains(steps.changeset.outputs.changes, 'frontend/web')) || (inputs.force_build) }}
        uses: ./.github/actions/deploy-web-aws-s3
        with:
          bucket_name: ${{ secrets.AWS_BUCKET_MAGISTRALES }}
          environment: qa-aws
          working_directory: ./frontend/web

      - name: Docker Build an Push Catalogos
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/catalogos-service
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: catalogosmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push OauthServer
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/oauthserver
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: oauthservermagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Pedidos
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/pedidos-service
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: pedidosmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Reporting
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/reporting-service
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: reportingmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push SapAdapter
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/sapadapter-service
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: sapadaptermagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Usuarios
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/usuarios-service
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: usuariosmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push Warehouses
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/warehouses-service
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: warehousesmagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Docker Build an Push SapServiceLayerAdapter
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build-aws
        with:
          working_directory: ./services/sapservicelayeradapter-service
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: sapservicelayeradaptermagistrales
          tag: ${{ github.sha }}
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_EKS_REGION }}

      - name: Deploy to EKS Magistrales
        working-directory: ./deploy/aws/qa
        run: |
          kubectl apply -f deploy.yml
          kubectl apply -f ingress-services.yml
          kubectl apply -f ingress-oauth.yml
          kubectl apply -f secrets.yml

      - name: Rollout catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy catalogos-deployment

      - name: Rollout oauthserver
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy oauthserver-deployment

      - name: Rollout pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy pedidos-deployment

      - name: Rollout reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy reporting-deployment

      - name: Rollout sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy sapadapter-deployment

      - name: Rollout usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy usuarios-deployment

      - name: Rollout warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy warehouses-deployment

      - name: Rollout sapservicelayeradapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy sapservicelayeradapter-deployment

      - name: Docker prune
        run: |
          docker builder prune -f -a
          docker image prune -f -a

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - de
      - build
    runs-on: [aws-bridge]
    permissions:
        actions: write
        contents: read
        id-token: write
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-east-2"
          role-to-assume: "arn:aws:iam::891376991292:role/GithubActionsRole"
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
