name: omicron-magistrales-sonar
on:
  workflow_dispatch:
    inputs:
      force_test:
        description: Force Test
        type: boolean
        default: false
        required: false
  pull_request:
    branches:
      - develop
      - release/qa
    paths:
      - frontend/**
      - services/**
      - batches/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
env:
  AWS_REGION: "us-east-2" # us-east-2 US East (Ohio) us-east-1" # US East (N. Viginia)
  AMI_ID: ami-0a68049ee64ac0782
  SUBNET_ID: subnet-073b7bac3af8d3c53
  SECURITY_GROUP_ID: sg-09c9844682ec712ca
  VOLUME_SIZE_GiB: "20"

jobs:
  start-runner:
    timeout-minutes: 5
    name: Start self-hosted EC2 runner
    runs-on: omicron-bastion
    permissions:
      actions: write
      contents: read
      id-token: write
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::891376991292:role/GithubActionsRole"
          output-credentials: true

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: Axitymx/ec2-action-builder@main
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ env.AWS_REGION }}
          ec2_instance_type: "t3.medium"
          ec2_ami_id: ${{ env.AMI_ID }}
          ec2_subnet_id: ${{ env.SUBNET_ID }}
          ec2_security_group_id: ${{ env.SECURITY_GROUP_ID }}
          ec2_root_disk_size_gb: ${{ env.VOLUME_SIZE_GiB }}
          ec2_spot_instance_strategy: "BestEffort"
          manual_stop: true

  test:
    name: Tests
    needs:
      - start-runner
    runs-on: ${{ github.run_id }}
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Set Environments
        uses: ./.github/actions/environments-aws

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::891376991292:role/GithubActionsRole"
          output-credentials: true

      - name: Generate CodeArtifact token
        id: codeartifact-token
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AXITY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AXITY_AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ""
          AWS_DEFAULT_REGION: us-east-1
        run: |
          unset AWS_SESSION_TOKEN
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain axity \
            --domain-owner 992382646884 \
            --region us-east-1 \
            --query authorizationToken \
            --output text)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT
          aws codeartifact login --tool dotnet \
            --domain axity \
            --domain-owner 992382646884 \
            --repository axity-nuget-repo \
            --region us-east-1

      - name: Test frontend/web
        if: ${{ (contains(steps.changeset.outputs.changes, 'frontend/web')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-web
        with:
          path: frontend/web
          project_name: web
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}

      - name: Test catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/catalogos-service
          project_name: Catalogos
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws

      - name: Test pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/pedidos-service
          project_name: Pedidos
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          net_version: 6.0.x
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws

      - name: Test reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/reporting-service
          project_name: Reporting
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws

      - name: Test sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/sapadapter-service
          project_name: SapAdapter
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws

      - name: Test usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/usuarios-service
          project_name: Usuarios
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws

      - name: Test warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net
        with:
          path: services/warehouses-service
          project_name: Warehouses
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws

      - name: Test sapservicelayeradapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net-v2
        with:
          path: services/sapservicelayeradapter-service
          project_name: SapServiceLayerAdapter
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws

      - name: Test invoice-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'invoice-service')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net-v2
        with:
          path: services/invoice-service
          project_name: Invoice
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws
      - name: Test productionorder-microbatch
        if: ${{ (contains(steps.changeset.outputs.changes, 'productionorder-microbatch')) || (inputs.force_test) }}
        uses: ./.github/actions/sonar-aws-net-v2
        with:
          path: batches/productionorder-microbatch
          project_name: FinalizeProductionOrder
          sonar_server: ${{ secrets.SONAR_SERVER }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          codeartifact_token: ${{ steps.codeartifact-token.outputs.token }}
          axity_user: aws
          
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - test
    runs-on: omicron-bastion
    permissions:
      actions: write
      contents: read
      id-token: write
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: "arn:aws:iam::891376991292:role/GithubActionsRole"
          output-credentials: true

      - name: Stop EC2 runner
        id: stop-ec2-runner
        uses: Axitymx/ec2-action-builder@main
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ env.AWS_REGION }}
          action: "stop"