name: omicron-magistrales-ios-sonar-v2
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - release/qa
    paths:
      - frontend/ios/**
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Cambiando a Ruby 3.3

      - name: Install dependencies
        working-directory: frontend/ios
        run: |
          sudo gem install cocoapods
          pod install
          brew install swiftlint

      - name: Install Fastlane
        uses: tashi-iu/setup-fastlane@v1
        with:
          version: '2.219.0' # Instalando Fastlane versi√≥n 2.219.0

      - name: Run ios sonar
        working-directory: frontend/ios
        run: bundle exec fastlane metrics
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_SERVER }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}