name: omicron-magistrales-prod
on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Force Build
        type: boolean
        default: false
        required: false
  push:
    branches:
      - master
    paths:
      - frontend/web/**
      - services/**
jobs:
  build:
    name: build environment
    runs-on: [self-hosted, omicron-qa]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Build frontend/web
        if: ${{ (contains(steps.changeset.outputs.changes, 'frontend/web')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: frontend/web
          environment: prod
          registry: omicron.azurecr.io
          configuration: production

      - name: Build catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/catalogos-service
          environment: prod
          registry: omicron.azurecr.io

      - name: Build oauthserver
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/oauthserver
          environment: prod
          registry: omicron.azurecr.io

      - name: Build pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/pedidos-service
          environment: prod
          registry: omicron.azurecr.io

      - name: Build reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/reporting-service
          environment: prod
          registry: omicron.azurecr.io

      - name: Build sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/sapadapter-service
          environment: prod
          registry: omicron.azurecr.io

      - name: Build usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/usuarios-service
          environment: prod
          registry: omicron.azurecr.io

      - name: Build warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/warehouses-service
          environment: prod
          registry: omicron.azurecr.io

      - name: Build sapservicelayeradapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/sapservicelayeradapter-service
          environment: prod
          registry: omicron.azurecr.io
          nexus_user: ${{ secrets.NEXUS_USER }}
          nexus_pass: ${{ secrets.NEXUS_PASS }}      

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2.2.4
        with:
          app-name: omicronlab
          images: omicron.azurecr.io/omicronprod/omicron-appiosformulas-web-repository:latest

      - name: Kubernetes deploy
        working-directory: deploy/prod
        run: |
          kubectl apply -f deploy_prod.yaml --context omicron-aks
          kubectl apply -f ingress-oauth.yml --context omicron-aks
          kubectl apply -f ingress-services.yml --context omicron-aks
          kubectl apply -f secretsprod.yml --context omicron-aks

      - name: Rollout catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy catalogos-deployment --context omicron-aks

      - name: Rollout oauthserver
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy oauthserver-deployment --context omicron-aks

      - name: Rollout pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy pedidos-deployment --context omicron-aks

      - name: Rollout reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy reporting-deployment --context omicron-aks

      - name: Rollout sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy sapadapter-deployment --context omicron-aks

      - name: Rollout usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy usuarios-deployment --context omicron-aks

      - name: Rollout warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy warehouses-deployment --context omicron-aks

      - name: Rollout sapservicelayeradapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapservicelayeradapter-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy sapservicelayeradapter-deployment --context omicron-aks        

      - name: Liquibase update
        working-directory: database/
        run: /opt/liquibase/liquibase --changeLogFile="changesets/db.changelog-master.xml" --defaultsFile="liquibase-prod.properties" update
      
      - name: Liquibase Soporte update
        working-directory: database/
        run: /opt/liquibase/liquibase --changeLogFile="changesets/db.changelog-soporte.xml" --defaultsFile="liquibase-prod.properties" update

      - name: Docker prune
        run: |
          docker builder prune -f -a
          docker image prune -f -a

      # - name: Microsoft Teams Notification
      #   uses: skitionek/notify-microsoft-teams@master
      #   if: ${{ always() }}
      #   with:
      #     webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
      #     needs: ${{ toJson(needs) }}
      #     job: ${{ toJson(job) }}
      #     steps: ${{ toJson(steps) }}
