name: omicron-magistrales-qa
on:
  workflow_dispatch:
    inputs:
      force_build:
        description: Force Build
        type: boolean
        default: false
        required: false
  push:
    branches:
      - release/Sprint12
    paths:
      - frontend/**
      - services/**
jobs:
  build:
    name: build docker images
    runs-on: [self-hosted, omicron-qa]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Build frontend/web
        if: ${{ (contains(steps.changeset.outputs.changes, 'frontend/web')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: frontend/web
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}

      - name: Build catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/catalogos-service
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}

      - name: Build oauthserver
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/oauthserver
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}

      - name: Build pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/pedidos-service
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}

      - name: Build reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/reporting-service
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}

      - name: Build sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/sapadapter-service
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}

      - name: Build usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/usuarios-service
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}

      - name: Build warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        uses: ./.github/actions/docker-build
        with:
          path: services/warehouses-service
          environment: qa
          registry: ${{ secrets.NEXUS_REGISTRY }}
  deploy:
    name: deploy to kubernetes cluster
    runs-on: [self-hosted, omicron-qa]
    needs: build
    steps:
      - name: Kubernetes deploy
        working-directory: deploy/qa
        run: |
          kubectl apply -f deploy_qa.yaml --context kubernetes-admin@kubernetes
          kubectl apply -f ingress-oauth.yml --context kubernetes-admin@kubernetes
          kubectl apply -f ingress-services.yml --context kubernetes-admin@kubernetes
          kubectl apply -f ingress-web.yml --context kubernetes-admin@kubernetes
  rollout:
    name: kubectl rollout
    runs-on: [self-hosted, omicron-qa]
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changeset
        id: changeset
        run: echo "changes=\"$(git diff HEAD HEAD~ --name-only | awk '{print}' ORS=' ')\"" >> $GITHUB_OUTPUT

      - name: Rollout frontend/web
        if: ${{ (contains(steps.changeset.outputs.changes, 'frontend/web')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy web-deployment --context kubernetes-admin@kubernetes

      - name: Rollout catalogos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'catalogos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy catalogos-deployment --context kubernetes-admin@kubernetes

      - name: Rollout oauthserver
        if: ${{ (contains(steps.changeset.outputs.changes, 'oauthserver')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy oauthserver-deployment --context kubernetes-admin@kubernetes

      - name: Rollout pedidos-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'pedidos-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy pedidos-deployment --context kubernetes-admin@kubernetes

      - name: Rollout reporting-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'reporting-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy reporting-deployment --context kubernetes-admin@kubernetes

      - name: Rollout sapadapter-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'sapadapter-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy sapadapter-deployment --context kubernetes-admin@kubernetes

      - name: Rollout usuarios-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'usuarios-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy usuarios-deployment --context kubernetes-admin@kubernetes

      - name: Rollout warehouses-service
        if: ${{ (contains(steps.changeset.outputs.changes, 'warehouses-service')) || (inputs.force_build) }}
        run: kubectl rollout restart deploy warehouses-deployment --context kubernetes-admin@kubernetes
  database:
    name: liquibase update
    runs-on: [self-hosted, omicron-qa]
    needs: rollout
    steps:
      - name: liquibase update
        working-directory: database/
        run: /opt/liquibase/liquibase --changeLogFile="changesets/db.changelog-master.xml" --defaultsFile="liquibase.properties" update
  clean:
    name: clean docker resources
    runs-on: [self-hosted, omicron-qa]
    needs: database
    steps:
      - name: Docker prune
        run: |
          docker builder prune -f -a
          docker image prune -f -a
  notify:
    name: teams notification
    runs-on: [self-hosted, omicron-qa]
    needs: database
    steps:
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: ${{ always() }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
